# Generated by Django 4.2.6 on 2023-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.CharField(max_length=50)),
                ('word_2', models.CharField(max_length=50)),
            ],
        ),
    ]
